\documentclass{article}

\usepackage{geometry}
  \geometry{
  a4paper,
  total={170mm,257mm},
  left=20mm,
  top=20mm,
  }

\usepackage{longtable}


\begin{document}

<<external-code, warning=FALSE, message=FALSE, echo=FALSE>>=
source('report-generator.R')

@

<<echo=FALSE, results="asis", message=FALSE, warning=FALSE>>=
library("xtable")
xt=xtable(df)

# print(params)

print(xt,
      tabular.environment = "longtable",
      floating = FALSE)

@

\end{document}