---
title: "GEEGLM"
author: "Tom Dalton"
date: "25/09/2017"
output: html_document

---

```{r}
setwd("/Users/tsd4/")

# This creates the panel ids. These are based on Source, Sex and YOB
path = "OneDrive/cs/PhD/code/population-model/validated/src/main/resources/results/geeglm/20170925-115556:076/tables/death-CT.csv"

data = read.csv(path, sep = ',', header = T)

data <- data[which(data$freq > 0.5),]
data$freq <- round(data$freq)
data <- data[which(data$Date < 2014),]
data <- data[which(data$Date > 1854),]


data.id = within(data, {
                 idvar = ifelse(Source == "SIM", 
                                ifelse(Sex == "MALE", as.numeric(paste("1", "1", YOB, sep = "")), as.numeric(paste("1", "2", YOB, sep = ""))),
                                ifelse(Sex == "MALE", as.numeric(paste("2", "1", YOB, sep = "")), as.numeric(paste("2", "2", YOB, sep = ""))))
                 })

data.id.sorted <- data.id[order(data.id$idvar, data$Age, data$Died),]
head(data.id.sorted, 25)
library(geepack)
mod2 <- geeglm(freq ~ Date * Age * Sex * Died * Source, id=idvar, data = data.id.sorted, corstr="ar1")
summary(mod2)

plot(residuals(mod2), type = "l")
plot(acf(residuals(mod2), lag.max = 10))
plot(acf(residuals(mod2), lag.max = 100))
plot(acf(residuals(mod2), lag.max = 1000))
plot(acf(residuals(mod2), lag.max = 10000))

require(mgcv)
fit<- gam(residuals(mod2) ~ s(data.id.sorted$idvar))
plot(fit)
summary(fit)

fit<- gam(residuals(mod2) ~ s(data.id.sorted$Date))
plot(fit)
summary(fit)

fit<- gam(residuals(mod2) ~ s(data.id.sorted$YOB))
plot(fit)
summary(fit)

```


```{r}
setwd("/Users/tsd4/")

# This creates the panel ids. These are based on Sex and YOB
path = "OneDrive/cs/PhD/code/population-model/validated/src/main/resources/results/geeglm/20170925-115556:076/tables/death-CT.csv"

data = read.csv(path, sep = ',', header = T)

data <- data[which(data$freq > 0.5),]
data$freq <- round(data$freq)
data <- data[which(data$Date < 2014),]
data <- data[which(data$Date > 1854),]

data.id = within(data, {
  idvar = ifelse(Source == "SIM", 
                 ifelse(Sex == "MALE", as.numeric(paste("1", "1", YOB, sep = "")), as.numeric(paste("1", "2", YOB, sep = ""))),
                 ifelse(Sex == "MALE", as.numeric(paste("1", "1", YOB, sep = "")), as.numeric(paste("1", "2", YOB, sep = ""))))
})

data.id.sorted <- data.id[order(data.id$idvar, data$Age, data$Died, data$Source),]
head(data.id.sorted, 25)
library(geepack)
mod2 <- geeglm(freq ~ Date * Age * Sex * Died * Source, id=idvar, data = data.id.sorted, corstr="ar1")
summary(mod2)

plot(residuals(mod2), type = "l")
plot(acf(residuals(mod2), lag.max = 10))
plot(acf(residuals(mod2), lag.max = 100))
plot(acf(residuals(mod2), lag.max = 1000))
plot(acf(residuals(mod2), lag.max = 10000))

require(mgcv)
fit<- gam(residuals(mod2) ~ s(data.id.sorted$idvar))
plot(fit)
summary(fit)

fit<- gam(residuals(mod2) ~ s(data.id.sorted$Date))
plot(fit)
summary(fit)

fit<- gam(residuals(mod2) ~ s(data.id.sorted$YOB))
plot(fit)
summary(fit)
```

