#!/bin/sh

# Add to .git/hooks/pre-commit in local project directory.

if grep -r '^ *results_save_location = /Users/gnck' 'src/test/resources/'; then
    echo "Commit blocked: debug mode is enabled."
    exit 1
fi

mvn license:check
if [ $? -ne 0 ]; then
    echo "Commit blocked: licence headers invalid."
    exit 1
fi
