name: Build and Test (Pull Request)

on:
  pull_request:
    branches: ['main']

jobs:
  build-and-test-linux:
    name: Build and test (Linux)
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out project
        uses: actions/checkout@v7.0.0

      - name: Build and run tests
        uses: ./.github/actions/build-and-test
        with:
          maven-target: 'package'
          maven-params: '-DexcludedGroups=slow'
