name: Build and Test (Push)

on:
  push:
    branches: ['main']
  workflow_dispatch:

concurrency:
  group: "build deploy"
  cancel-in-progress: true

jobs:
  build-and-test-linux:
    name: Build and test (Linux)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out project
        uses: actions/checkout@v7.0.0

      - name: Build and run tests
        uses: ./.github/actions/build-and-test
        with:
          maven-target: 'package'
          maven-params: '-DexcludedGroups=slow'
          # Disabled while gedinline dependency is handled as a local jar.
          # upload-dependencies: 'true'

  build-pages:
    name: Build website
    needs: build-and-test-linux
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: Build docs
        uses: ./.github/actions/build-docs

  deploy-pages:
    name: Deploy website
    needs: build-pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5.0.0
